import { db } from '@/db';
import { sponsorshipRequests } from '@/db/schema';

async function main() {
    const sampleSponsorshipRequests = [
        {
            requestId: 1,
            type: 'vendor',
            tier: 'standard',
            status: 'pending',
            requestDate: new Date('2024-11-05').toISOString(),
            processedDate: null,
            vendorId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            productId: null,
            monthlyFee: 49,
            commission: 12,
            message: "I've been selling successfully for 6 months and want to boost visibility for my entire store. My products have maintained a 4.7 average rating.",
            adminNotes: null,
        },
        {
            requestId: 2,
            type: 'product',
            tier: 'standard',
            status: 'pending',
            requestDate: new Date('2024-11-12').toISOString(),
            processedDate: null,
            vendorId: 'user_02k5myt3f9a1z4c2o8n7r6x9s5',
            productId: 23,
            monthlyFee: 49,
            commission: 12,
            message: "This is my best-selling product with 4.8 stars and over 200 sales. I'd like to feature it on the homepage to reach more customers.",
            adminNotes: null,
        },
        {
            requestId: 3,
            type: 'vendor',
            tier: 'premium',
            status: 'approved',
            requestDate: new Date('2024-10-20').toISOString(),
            processedDate: new Date('2024-10-25').toISOString(),
            vendorId: 'user_03l6nzu4g0b2a5d3p9o8s7y0t6',
            productId: null,
            monthlyFee: 99,
            commission: 8,
            message: "I have 15 high-quality WordPress themes with excellent reviews. Premium sponsorship would help establish my brand as a top seller on the platform.",
            adminNotes: "Strong sales record with 500+ total sales and 4.9 rating. Approved for 30 days. Excellent product quality and customer service history.",
        },
        {
            requestId: 4,
            type: 'product',
            tier: 'standard',
            status: 'pending',
            requestDate: new Date('2024-11-18').toISOString(),
            processedDate: null,
            vendorId: 'user_04m7ova5h1c3b6e4q0p9t8z1u7',
            productId: 45,
            monthlyFee: 49,
            commission: 12,
            message: "My UI kit has been consistently in the top 10 for 3 months. Sponsorship would help maintain momentum and reach design teams looking for professional components.",
            adminNotes: null,
        },
        {
            requestId: 5,
            type: 'vendor',
            tier: 'standard',
            status: 'rejected',
            requestDate: new Date('2024-11-01').toISOString(),
            processedDate: new Date('2024-11-03').toISOString(),
            vendorId: 'user_05n8pwb6i2d4c7f5r1q0u9a2v8',
            productId: null,
            monthlyFee: 49,
            commission: 12,
            message: "I just launched my store 3 weeks ago and have 2 products. Looking to get initial traction through sponsorship.",
            adminNotes: "Account too new - requires 60 days active sales history and minimum 5 products. Suggest reapplying after meeting requirements.",
        },
        {
            requestId: 6,
            type: 'product',
            tier: 'premium',
            status: 'approved',
            requestDate: new Date('2024-10-15').toISOString(),
            processedDate: new Date('2024-10-20').toISOString(),
            vendorId: 'user_06o9qxc7j3e5d8g6s2r1v0b3w9',
            productId: 12,
            monthlyFee: 99,
            commission: 8,
            message: "Premium WordPress theme with 350+ sales and 4.9 rating. Featured by Envato last month. Ready to invest in premium placement for maximum visibility.",
            adminNotes: "Exceptional product with proven track record. Premium tier approved. Featured homepage placement granted for 30 days with priority support.",
        },
        {
            requestId: 7,
            type: 'vendor',
            tier: 'standard',
            status: 'approved',
            requestDate: new Date('2024-10-28').toISOString(),
            processedDate: new Date('2024-11-02').toISOString(),
            vendorId: 'user_07p0ryd8k4f6e9h7t3s2w1c4x0',
            productId: null,
            monthlyFee: 49,
            commission: 12,
            message: "Active seller for 8 months with 12 products. Average 4.6 rating across all items. Sponsorship will help compete with established sellers.",
            adminNotes: "Solid performance metrics. Approved for initial 30-day trial. Monitor engagement and conversion rates for potential premium upgrade path.",
        },
        {
            requestId: 8,
            type: 'product',
            tier: 'standard',
            status: 'rejected',
            requestDate: new Date('2024-11-08').toISOString(),
            processedDate: new Date('2024-11-13').toISOString(),
            vendorId: 'user_08q1sze9l5g7f0i8u4t3x2d5y1',
            productId: 34,
            monthlyFee: 49,
            commission: 12,
            message: "New plugin launch with innovative features. Want to sponsor to get initial reviews and traction.",
            adminNotes: "Product has only 2 sales and 1 review (3 stars). Needs to establish quality track record first. Minimum 10 sales and 4+ rating required.",
        },
        {
            requestId: 9,
            type: 'vendor',
            tier: 'premium',
            status: 'rejected',
            requestDate: new Date('2024-10-25').toISOString(),
            processedDate: new Date('2024-10-30').toISOString(),
            vendorId: 'user_09r2taf0m6h8g1j9v5u4y3e6z2',
            productId: null,
            monthlyFee: 99,
            commission: 8,
            message: "I sell premium design templates. Want maximum exposure for my store. Have 8 products with good sales.",
            adminNotes: "Recent customer service issues flagged. 3 refund requests in past month. Need to resolve outstanding support tickets before sponsorship approval.",
        },
        {
            requestId: 10,
            type: 'product',
            tier: 'standard',
            status: 'pending',
            requestDate: new Date('2024-11-22').toISOString(),
            processedDate: null,
            vendorId: 'user_10s3ubg1n7i9h2k0w6v5z4f7a3',
            productId: 18,
            monthlyFee: 49,
            commission: 12,
            message: "E-commerce WordPress theme with 180 sales and 4.7 rating. Holiday season approaching - perfect time to sponsor for increased visibility during peak shopping period.",
            adminNotes: null,
        },
    ];

    await db.insert(sponsorshipRequests).values(sampleSponsorshipRequests);
    
    console.log('✅ Sponsorship requests seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});